
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import Box from '@mui/material/Box';
import { red } from "@mui/material/colors";

import Header from '@/app/components/Header'
import Navigator from '@/app/components/Navigator'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AppRouterCacheProvider>
          <Navigator />
          {/* <Header  /> */}
         
          {/* <Box sx={{ width: '100%', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 2 }}>
            <Box sx={{ bgcolor: 'red' }} >栅格项 1</Box>
            <Box>栅格项 2</Box>
            <Box>栅格项 3</Box>
          </Box> */}

          {children}

        </AppRouterCacheProvider>

      </body>
    </html>
  );
}
