import Image from 'next/image'

import type { Metadata } from "next";

import apng from '@/public/images/a.png'

export const metadata: Metadata = { 
    title: "a1",
    description: "Generated by create next app",
  };

export default function a1() {

    return (

        <div >
            <nav className="bg-gradient-to-r from-indigo-600 to-slate-800 text-white p-4 flex items-center justify-between">
                <div>
                    {/* Logo 或网站名称 */}
                    <span className="font-bold">你的网站名称</span>
                </div>
                <div className="w-2/3">
                    <ul className="flex items-center space-x-4">
                        {/* 导航链接 */}
                        <li><a href="/" className="hover:text-gray-300">首页</a></li>
                        <li><a href="/about" className="hover:text-gray-300">关于我们</a></li>
                        <li><a href="/services" className="hover:text-gray-300">服务</a></li>
                        <li><a href="/contact" className="hover:text-gray-300">联系我们</a></li>
                    </ul>

                </div>
                <ul className="flex items-center space-x-4">
                    {/* 导航链接 */}
                    <li><a href="/" className="hover:text-gray-300">首页</a></li>
                    <li><a href="/about" className="hover:text-gray-300">关于我们</a></li>

                </ul>
            </nav>



            <div className="flex items-center justify-center bg-black">
                <Image width={100} src={apng} alt='gg' />
                <div className='text-white bg-blue-200'>
                    <strong>Andrew Alfred</strong><br></br>
                    <span>Technical advisor</span>
                </div>
            </div>



            <div className="bg-yellow-300 w-52 h-20">
                <Image className="object-cover" src={apng} alt='gg' />
            </div>


            <div className="w-40 h-40 bg-blue-300 p-4 overflow-visible">
                <p>This is a very long text that will exceed the container's height.</p>
            </div>












        </div>
    )
}